### ISSUE TITLE
error: omsconfig:1 glob failed for /opt/omi/var/log/*.log: No such file or directory

### ISSUE THREAD

**Issue by sjohner** [Microsoft/OMS-Agent-for-Linux#11]
Omsconfig logrotate config does not seem to be correct or rather refers to unavailable log folder /opt/omi/var/log

![untitled](https://cloud.githubusercontent.com/assets/16019080/12402614/71b0c6d4-be2e-11e5-86f7-09804c32b1ff.png)

**Comment by niroyb** [comment]
Looks like it should be `/var/opt/omi/log/*.log` instead of `/var/opt/omi/log/`

**Comment by jeffaco** [comment]
I think this is a little more involved:

1. I don't think omsconfig should be responsible for trimming OMI's log file, I think OMI should be responsible for it.
2. I think we can do an omiserver reload operation rather than a omiserver restart operation (although this is minor).

Let's briefly discuss at tomorrow's scrum to bring this to closure.

**Comment by jeffaco** [comment]
Give us a little while on this, we're swamped with other issues right now. In the meantime, if you want things to work properly change /opt/omi/var/log/*.log to:

/var/opt/omi/log/*.log

In general, OMI logs very, very little, so this isn't an urgent issue. But it is something we want to fix.

/Jeff

**Comment by sjohner** [comment]
No problem, thanks for getting back to me!

**Comment by jeffaco** [comment]
This will be fixed in OMSAgent build 1.1.0-35 or later.

Thanks for letting us know about this!

**Comment by sjohner** [comment]
Thanks guys!
