### ISSUE TITLE
OMS-agent CEF forwarder

### ISSUE THREAD

**Issue by ChessSpider** [microsoft/OMS-Agent-for-Linux#1150]
Hi,
I want to forward events in CEF format into Microsoft Sentinel. All I need is a simple forwarder which listens on a port (syslog events) and forwards it into Microsoft Sentinel in CEF format.

This guide redirects me here: https://docs.microsoft.com/en-us/azure/sentinel/connect-common-event-format

However, the OMS-Agent-for-Linux appears to do a lot of extra things, and the requirement to have the workspace-id and primary key present upon installation does not work for our Docker-pipeline. 

How can i use OMS-Agent in Docker to forward CEF events into Sentinel, configuring the workspace-id and key using configuration variables _after_ the installation steps? 

Or is there an easier way to ingest data into Sentinel, without OMS-Agent?

**Comment by profesor79** [comment]
you can load events using log analytics api (that require to convert data into json),
but gives you full flexibility over the ingestion.
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api

**Comment by haiderim** [comment]
You can make omsagent listen to a socket like 0.0.0.0:25224 instead of loopback socket, 127.0.0.1:25224 if you don't want to deal with rsyslog or syslog-ng. It's only a matter of changing the config present in /etc/opt/microsoft/omsagent/conf/omsagent.d/syslog.conf and restarting the service. You can repeat the same procedure for cef listener, the filename being security_events.conf.

**Comment by ciyaresh** [comment]
@ChessSpider where you able to find a solution to this problem?
