### ISSUE TITLE
Latest GA build didn't update the installer version correctly

### ISSUE THREAD

**Issue by coolbreezer** [microsoft/OMS-Agent-for-Linux#1243]
The installer onboard_agent.sh still use the v1.12.15 to download omsagent for x86_64 in release build GA v1.13.9-0. I would like to know is that intend or we have to update the version in onboard_agent.sh

**Comment by haiderim** [comment]
This shouldn't happen atleast according to the script here

https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/onboard_agent.sh

**Comment by coolbreezer** [comment]
I downloaded from https://github.com/microsoft/oms-agent-for-linux/releases with v1.13.9-0 tag or via raw (https://raw.githubusercontent.com/microsoft/OMS-Agent-for-Linux/OMSAgent_v1.13.9-0/installer/scripts/onboard_agent.sh)

**Comment by haiderim** [comment]
Yeah the one you've linked does indeed refer an older release

**Comment by hestolz** [comment]
Hi @coolbreezer, there was a line item for 1.13.7-0 that was not carried forward to the next releases (I re-added it to 1.13.27-0). We noted that 1.12.15-0 is the last 32-bit release, going forward due to transition to a modernized build system we can no longer provide 32-bit bundles. If you are unable to migrate to 64-bit, you can try building the newer release tags with your own build system. Unfortunately, we can't provide guidance for such a process and won't be able to support any agents built or installed this way.
