### ISSUE TITLE
OMS Agent not uploading up any custom log data when log file is first generated

### ISSUE THREAD

**Issue by aluong** [microsoft/OMS-Agent-for-Linux#1341]
I was follow the following [doc](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/data-sources-custom-logs) to configure custom logs.

**Actual**
If I drop a log file with data into the path where the custom log is looking, I notice that none of that data is being uploaded. However, if I append to that log file, it looks like that data is being picked up.

```
$ echo Test1 > test.log
$ echo Test2 >> test.log
$ echo Test3 >> test.log
```

I will see the "Test2" log entry and the "Test3" log entry in log analytics. However, "Test1" is missing.

**Expected**
In addition to all of the appended lines toa. log file, I expect that I would see all of the data in the log file uploaded when the log file is created. (i.e. log entries for "Test1", "Test2", and "Test3" in Log Analytics)

**Comment by aswatt** [comment]
Hi @aluong , this is actually expected behavior for the OMS Agent - it only grabs logs that were added to the file after it has started being tailed. This was an intentional decision made when creating the custom logs for OMS initially.

I believe this is occurring because OMS considers Test1 to be part of the file before it had started being tailed, and so doesn't send those lines. Test2 and Test3 were added after OMS had started tailing the file, and so it sent those lines.

I hope this helps explain this situation. Thank you!
