### ISSUE TITLE
Update OMI part of OmsAgentForLinux from 1.6.8-0 to OMI 1.6.8-1

### ISSUE THREAD

**Issue by mbsnl** [microsoft/OMS-Agent-for-Linux#1359]
Regarding the OMIGOD vulnerability, please update OMI part of OmsAgentForLinux from 1.6.8-0 to OMI 1.6.8-1 on new and existing installations. See:
https://github.com/microsoft/omi/issues/694
https://github.com/microsoft/omi/releases/tag/v1.6.8-1

**Comment by hestolz** [comment]
The team is aware, we are currently generating a release using the fixed OMI version and will publish the release once verified.

**Comment by hestolz** [comment]
Hi @mbsnl, The release 1.13.40 incorporating OMI 1.6.8-1 is [released](https://github.com/microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent_v1.13.40-0).

**Comment by flannoo** [comment]
How is this vulnerability impacting PaaS services in Azure (App Service, Azure Kubernetes Service, ...) with underlying linux VM's? Does the OMI vulnerability affect those services as well? Because we don't have access to perform the patch on those VM's, since Microsoft controls that infrastructure.

**Comment by NarineM** [comment]
Fixed in oms agent versions starting 1.14.11.
