### ISSUE TITLE
FluentD debug tracing

### ISSUE THREAD

**Issue by ChrisHeitkamp** [Microsoft/OMS-Agent-for-Linux#26]
No real issue, but rather a CR:
It would be good if the omsagent / fluentd call could have debug parameters passed (-vv) when service_control is called with a debug level. 

>> START_QUALS="-d $PIDFILE --no-supervisor -o $LOGFILE -vv" <<

And my question:
Even with -vv  I do not get plugin tracing information. 
Looking for lines like 
log.debug "Success sending #{tag} x #{count} in #{time.round(2)}s"
from the out_oms plugin.
Any hints?

**Comment by jeffaco** [comment]
While it's not difficult modifying service_control to take a debug level, note that the various mechanisms used to start across various systems (be it /etc/inid.d style scripts or systemd control) do not necessarily take a parameter. I could set something globally and detect at startup, but that seems kind of sloppy to me.

As for the -vv option to fluentd, we're using the fluentd framework, and we're checking for debug of our particular plugin. Debugging globally (what -vv does) doesn't appear to set individual plugins to debug, which is why that's happening.

Given what you're after, I think it's easier just to change the configuration to debug our plugin.

Hope this helps,

/Jeff

**Comment by niroyb** [comment]
To answer the second part of the question, there are two types of log levels in fluentd:

1. The global logging level controlled on invocation with the -v or -vv flags affects `$log`.
2. The per plugging logging level controlled by the `log_level` tag in the configuration script  affects `@log`. 

In this case [per plugin logging is used](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/9b438241c8c1d069931d81726041aa47b8307940/source/code/plugins/out_oms.rb#L52). Change the [log_level of the output plugin](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/c97d90a4bf74344e067d8df081c740f8f4d3f61e/installer/conf/omsagent.conf#L94) to debug. The configuration file is located in `/etc/opt/microsoft/omsagent/conf/omsagent.conf`
Additional documentation can be found here : http://docs.fluentd.org/articles/logging#per-plugin-log

**Comment by jeffaco** [comment]
@ChrisHeitkamp, have we answered your questions? If so, please feel free to close this issue. If not, please post a new comment and we'll help you out.

**Comment by ChrisHeitkamp** [comment]
@jeffaco @niroyb, thanks, this was the information I needed.
