### ISSUE TITLE
Any documentation on how to write own .conf files? Needed for custom query to MySQL

### ISSUE THREAD

**Issue by gunnarstolz** [Microsoft/OMS-Agent-for-Linux#331]
For monitoring of our MySQL-cluster I would like to add an additional <source> Element to mysql.conf, which should execute a query like "SELECT 1 FROM dual;".
Unfortunately I cannot find any documentation on how the attributes of <source> element should be used.
What I did find were examples on how to use "tail log" or "execute scripts". So, what I tried was to execute an SQL query as mysql-client-command: mysql -u -p -e "SELECT 1 FROM dual;". This didn't throw any error in the log, but didn't anything either.
I hope someone has a hint for me.
Thanks a lot in advance!

**Comment by robbiezhang** [comment]
The exec and tail plugin are fluentd built-in ones. You can find the document here: 
http://docs.fluentd.org/articles/in_exec
http://docs.fluentd.org/articles/in_tail

You can to make the tag like "oms.api.[type]", it will use the out_oms_api plugin to send the data to OMS.
Please also make sure the out put of the command is a simple json (not an array, no json as property). Otherwise, you can use the filter_flatten plugin to flatten the json
<filter oms.api.[type]>
  type filter_flatten
</filter>
