### ISSUE TITLE
process_stats_ files never deleted

### ISSUE THREAD

**Issue by brandubh** [Microsoft/OMS-Agent-for-Linux#357]
thousands of process_stats_* files are created and never deleted in /var/opt/microsoft/omsagent/tmp 
If I can point a finger, I would say: source/code/plugins/agent_topology_request_script.rb

**Comment by keikhara** [comment]
@brandubh Can you provide which version of the agent this is? thanks.

**Comment by lagalbra** [comment]
@brandubh Can you provide the content of one of these files?

I do not believe that [agent_topology_request_script.rb](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/source/code/plugins/agent_topology_request_script.rb) is causing the issue, as it never creates a file.

**Comment by lagalbra** [comment]
@brandubh According to our investigation, this issue was resolved with the latest agent release, [1.2.0-148](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/tag/OMSAgent-201610-v1.2.0-148). Can you confirm that your agent is older than this, or that any process_stats_* files were created before the date when you upgraded to the 1.2.0-148 version?

Once you have upgraded, you will have to delete those files in tmp/ manually.

**Comment by lagalbra** [comment]
@shaneholloman @rjcrystal Please verify that using the [latest agent release](https://github.com/Microsoft/OMS-Agent-for-Linux/releases/latest) (now 1.3.2-15) resolves this issue. If this error still occurs, please update this thread; otherwise, this issue will be closed.

**Comment by NarineM** [comment]
@brandubh 
OMSagent no longer serializes telemetry data in process_stats* tmp files starting release >= 1.2.0-148. This issue has been fixed.
