### ISSUE TITLE
Versions and where to find them?!

### ISSUE THREAD

**Issue by atmosx** [Microsoft/OMS-Agent-for-Linux#383]
Hi,

Your [documentation](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#the-oms-agent-for-linux) refers to version `1.3.x` while all installation methods mentioned in Azure panel and here (see README) refer to  version `1.2.x` which is utterly confusing.

I tried branch `OMSAgent-201702-v1.3.1-15` but the `onboard_agent.sh` is exactly the same as master. I can not see `omsagent-1.3.0-1.universal.x64.sh` file, as referenced in the documentation. 

Is there a way to install version 1.3?

**Comment by NarineM** [comment]
Hi @atmosx 
Here are all GitHub omsagent releases you can use: https://github.com/Microsoft/OMS-Agent-for-Linux/releases

The documentation was updated to refer to 1.3.x as the first release that would contain multi-homing feature. Today that version is only available through Azure VM extension.
If you are not depending on multi-homing (onboarding of the same agent to multiple workspaces) you can use any of the versions from the above link. 
There would be 1.3.x release coming up soon that would be available on GitHub as well as in Azure VM extension in case you are interested in trying out the new features. I am going to close this issue since no other follow up is required at this point.

**Comment by NarineM** [comment]
@atmosx 
I can also replace 0-1 references with 1.3.x in the doc to make it clear.

**Comment by atmosx** [comment]
Thanks for the comment @NarineM !
