### ISSUE TITLE
Follow Docker-Instructions.md gets dial tcp 127.0.0.1: 25225: connection refused

### ISSUE THREAD

**Issue by jmacias** [Microsoft/OMS-Agent-for-Linux#47]
I created a VM using ARM using OmsAgentForLinux and the DockerExtension, the docker extension was initialized using the docker options has specified on the doc, `"options": ["--log-driver=fluentd", "--log-opt",  "fluentd-address=localhost:25225"] `. After a successful provision `ps` shows the correct process:

```
omsagent 36326     1  0 22:29 ?        00:00:01 /opt/microsoft/omsagent/ruby/bin/ruby /opt/microsoft/omsagent/bin/omsagent -d /var/opt/microsoft/omsagent/run/omsagent.pid --no-supervisor -o /var/opt/microsoft/omsagent/log/omsagent.log
root     36399     1  0 22:30 ?        00:00:00 /usr/bin/docker daemon -H=unix:// --log-driver=fluentd --log-opt fluentd-address=localhost:25225
``` 
But when I try to run a Docker container I get the error `dial tcp 127.0.0.1: 25225: connection refused`. The problem is that the OmsAgentForLinux  does not start the TCP Service on 25225, it only has the UDP at 25224. This was shown by `netstat -tulpn` 

After updating `/etc/opt/microsoft/omsagent/conf/omsagent.conf` and re-starting, to start the service on TCP@25225 - as instructed here: https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/docs/OMS-Agent-for-Linux.md#enabling-high-volume-syslog-event-collection - I was able to start my Docker Container

Two questions:
   1. ***Did I take the right actions?*** I still see the message `Operations Management Suite is connecting to your server ` on the `Containers Panel`
   2. ***Are the instructions incorrect?*** 

Thanks for your help!

**Comment by jeffaco** [comment]
@agup006 Can  you take a look at this, provide guidance, and correct docs if needed?

**Comment by jeffaco** [comment]
@agup006 Did you take a look at this? Can this issue be closed?

**Comment by jmacias** [comment]
@jeffaco 
I think the instructions are correct since as prerequisite of using OMS with Docker is:

```
Your container hosts must be running:

Docker 1.8 or later
```

My original  intention was to set up a Linux VM using an ARM Template with the following:

-  Docker Extension 
- OMS Monitoring the Docker Containers 

The problem with this approach is that OMS won't enable Docker monitoring if Docker is not installed. You could first use the docker extension and then the OMS extension but this would fail by "log-driver=fluentd" docker start-up parameter - since the service is started by the OMS Extension. 

I think a possible solution could be to flag the OMS extension to enable Docker Monitoring even if is not currently installed. A Workaround would be to  have a custom script to restart the docker server as the last step on the ARM Template.

Thanks for your help!

**Comment by jeffaco** [comment]
@jmacias I'm somewhat confused by your message.

Unfortunately, I don't know a lot about the Docker extension, but I know enough where we can hopefully help each other.

Normally, we only listen for log messages via UDP 25225. We do this because it's "lower weight", and generally sufficient for us to capture all logging information. But we later learned that, under very high message loads (like ~1000 messages/second), messages can be lost (even on the same system) with UDP, and you really needed TCP. So we did some optimization work to make OMS more efficient with batching, and we documented how to enable TCP/IP if you needed it.

So, with that explained, are you saying that Docker will only work with TCP/IP enabled (it won't work otherwise)? If so, that's definitely a documentation problem, and Anurag will need to fix that. Or are you saying something else?

Next, I don't fully understand your issue. The Docker agent does require that Docker be installed (it uses Docker directly). And you're running Docker containers, so you must have Docker installed, right?

The message on the portal is from someone else; I can refer him to this thread if needed. But right now, I'd just like to clearly and succinctly understand your issues.

Thanks, and sorry for my confusion. There's multiple teams maintaining different components, and I need to clearly understand what's happening so I can involve the proper teams.

**Comment by hunty1** [comment]
I'm having the same issue. TCP port 25225 is not running.
There is a tcp port 24220 and a UDP port 25224 coming from a ruby script which I assume is the OMS agent.

following the instructions exactly, on multiple machines, port 25225 is never running.

Host OS is Centos 7.1
Docker v 1.9.1
omsagent version 1.1.0-239

**Comment by agup006** [comment]
Hi all, In some cases the docker configuration does not get loaded as part of the agent install. The `container.conf` file can be found [here](https://github.com/Microsoft/Docker-Provider/blob/master/installer/conf/container.conf) - and can be copied over to /etc/opt/microsoft/omsagent/conf/omsagent.d/. 

This configuration file opens the port to listen for logs being sent from the docker daemon.
