### ISSUE TITLE
Automation - Update management (Preview) all VMs Not-Assessed EXCEPT ONE VM.

### ISSUE THREAD

**Issue by tkomlichenko** [microsoft/OMS-Agent-for-Linux#641]
Hi,
we just started to use the Update Management in Azure Portal. 
After creating the Workspace and adding several VMs to it, we can see them showed green and with OMS connection as "This Workspace in "Workspace->Virtual Machines ". 
After several days, we can see only one VM Non-Compliant in the "Update management (Preview)". The rest of the VMs are showed as "not assessed".
We have Windows and Linux Suse VMs. All created in Azure Portal and added to the Workspace exactly the same way. All prerequisites are met. We kept VMs running for several days, then restarted some of them. OMS agent logs don't show errors. All seams fine. 
What could we check?

**Comment by tkomlichenko** [comment]
More info: all the VMs Agents are "sending OMS Heartbeat succeeded" as per  /var/opt/microsoft/omsagent/log # tail -100 omsagent.log
Why one VM is assessed and another not? There is no refresh button on the "Update management (Preview)" page. Does it make sense to have this button or this page has autorefresh?
BR

**Comment by aydeisen** [comment]
I'm having a similar issue.  If I'm reading the scripts correctly, it appears that the script `patch_management_lib.rb` is dependent on the included Linux DSC resource ``nxAvailableUpdates.py`.  However, installing the [PowerShell DSC Agent for Linux](https://github.com/Microsoft/PowerShell-DSC-for-Linux) is not part of the `omsagent-*.sh` script to install OMS.  Since the DSC Agent is apparently a requirement for full OMS functionality on Linux, can it be included in the installer scripts?

**Comment by NarineM** [comment]
@Atchub @shuliums can you take a look?

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
