### ISSUE TITLE
Insane amount of logs being generated into /var/log/auth.log

### ISSUE THREAD

**Issue by LukeStonehm** [Microsoft/OMS-Agent-for-Linux#849]
Good day.

We are seeing some seriously bad behavior from the OMS Agent. Currently I am unable to diagnose what is the cause. Here is a snippet of the log as found in `/var/log/auth.log`. Some details have been removed due to their sensitive nature.

```
Nov 15 17:09:39 SERVERNAME sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 15 17:09:39 SERVERNAME sudo: pam_unix(sudo:session): session closed for user root
Nov 15 17:09:39 SERVERNAME sudo: omsagent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/docker inspect --format={{.LogPath}} 6c57bb83bd12ae58dbe03df66d28fd659d750eee68f65585dbd372ac32990fcc
Nov 15 17:09:39 SERVERNAME sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
Nov 15 17:09:39 SERVERNAME sudo: pam_unix(sudo:session): session closed for user root
Nov 15 17:09:39 SERVERNAME sudo: omsagent : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/test -r /var/lib/docker/containers/6c57bb83bd12ae58dbe03df66d28fd659d750eee68f65585dbd372ac32990fcc/6c57bb83bd12ae58dbe03df66d28fd659d750eee68f65585dbd372ac32990fcc-json.log
```

This is repeated continuously, and was consuming over 2gb before I truncated. 

EDIT: I've watched how frequently it's logging. Every 10 seconds it's consuming +/- 120KBs. This translates to roughly 1GB a day. Obviously after the main `auth.log` reaches a particular size, the system will move the logs into a GZIP-ed archive. This still is not good enough, and the space wears thin after some time.

**Comment by purplekrayons** [comment]
Luke, this is not a result of the omsagent itself, rather, this is a natural function of linux. By default, linux logs all sudo commands issued by users. The omsagent runs with elevated privileges (sudo), and since its constantly collecting data from your virtual machine, it naturally produces a large number of logs.

You can disable sudo logging for users in linux, by editing the `sudoers` file. It is **extremely** important that you edit this file using `visudo`. Do not, under any circumstance, try and edit this file using `vi` or `nano`. You've been warned.

Now, to disable sudo logging for the omsagent, edit the sudoers file using visudo like this:

`sudo visudo`

Then, add this line somewhere near the top:

```
Defaults:omsagent !syslog
```

Here's a snapshot of what it should look like.

![visudo](https://user-images.githubusercontent.com/9218035/51873605-d83db780-232b-11e9-9825-f1c60425f8f6.JPG)

Please be sure to close this issue if this has resolved your issue.
Thanks.

**Comment by LukeStonehm** [comment]
Thanks @purplekrayons

We actually already did this I believe. I wasn't responsible for the change, but I do believe it has resolved the issue. 

I will say that the agent was running for more than half a year before this issue cropped up, and seemed to only begin causing us issues after an update. 

Regardless, we have resolved the issue, thank you for you response.
