### ISSUE TITLE
nxOMSAutomationWorker not installing after reinstall

### ISSUE THREAD

**Issue by 1trevor** [microsoft/OMS-Agent-for-Linux#877]
I am following the instructions here to register a Linux hybrid worker with Azure Automation: https://docs.microsoft.com/en-us/azure/automation/automation-linux-hrw-install

On the first install everything installed fine but while troubleshooting some issues I decided to re-install per these instructions: https://support.microsoft.com/en-us/help/4131455/how-to-reinstall-operations-management-suite-oms-agent-for-linux

After reinstalling, the /opt/microsoft/omsconfig/modules/nxOMSAutomationWorker folder does not exist and according to the output of onboard_agent.sh, that module was not installed.

I have tried uninstalling/unregistering and reinstalling/reregistering multiple times and the nxOMSAutomationWorker never comes back the way it did on initial install.

Any help would be greatly appreciated.

**Comment by ramuadapa** [comment]
I am also facing the same issue, InstallModule.py not downloading the "nxOMSAutomationWorker" module.

Looking forward for help or suggestions.

**Comment by larry-b-it** [comment]
I'm running into this issue also, even when testing by installing a new empty linux vm:

omsconfig.log:

....
VERBOSE from OMS_MetaConfigHelper.py: Successfully configured omsconfig.
[2020/04/23 18:45:01] [53512] [INFO] [0] [/opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py:0] dsc_host lock file is acquired by : PerformRequiredConfigurationChecks
VERBOSE from InstallModule.py: Extracting module zip file from /tmp/fileUFMoLG/nxOMSPlugin_3.34.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxOMSPluginResource
VERBOSE from InstallModule.py: Updated permissions of file: /opt/omi/lib/libMSFT_nxOMSPluginResource_root-oms.so to 0644
VERBOSE from InstallModule.py: Updated permissions of file: /opt/dsc/lib/MSFT_nxOMSPluginResource/libMSFT_nxOMSPluginResource.so to 0644
VERBOSE from InstallModule.py: Updated permissions of file: /etc/opt/omi/conf/omiregister/root-oms/MSFT_nxOMSPluginResource.reg to 0644
VERBOSE from InstallModule.py: Extracting module zip file from /tmp/fileUFMoLG/nxOMSGenerateInventoryMof_1.3.zip to /opt/microsoft/omsconfig/modules
VERBOSE from InstallModule.py: Installing resource MSFT_nxOMSGenerateInventoryMofResource
VERBOSE from InstallModule.py: Updated permissions of file: /opt/omi/lib/libMSFT_nxOMSGenerateInventoryMofResource_root-oms.so to 0644
VERBOSE from InstallModule.py: Updated permissions of file: /opt/dsc/lib/MSFT_nxOMSGenerateInventoryMofResource/libMSFT_nxOMSGenerateInventoryMofResource.so to 0644
VERBOSE from InstallModule.py: Updated permissions of file: /etc/opt/omi/conf/omiregister/root-oms/MSFT_nxOMSGenerateInventoryMofResource.reg to 0644
2020/04/23 18:46:06: ERROR: null(0): EventId=1 Priority=ERROR Job 76C48EA0-2EE4-4DC1-A3F5-D04CF1CA1888 : 
DSC Engine Error : 
	 **Error Message Pull server with url: 2c1a3a3a-89eb-4ca8-9df3-4ae4f02394b1.agentsvc.azure-automation.net responded with error code: 404 for module 'nxOMSAutomationWorker' version '1.6.9.2'**. 
	Error Code : 1 
2020/04/23 18:46:06: ERROR: null(0): EventId=1 Priority=ERROR Job 76C48EA0-2EE4-4DC1-A3F5-D04CF1CA1888 : 
This event indicates that failure happens when LCM is trying to get the configuration from pull server using download manager null. ErrorId is 1. ErrorDetail is Pull server with url: 2c1a3a3a-89eb-4ca8-9df3-4ae4f02394b1.agentsvc.azure-automation.net responded with error code: 404 for module 'nxOMSAutomationWorker' version '1.6.9.2'.
[2020/04/23 19:00:01] [57103] [INFO] [0] [/opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py:0] dsc_host lock file is acquired by : PerformRequiredConfigurationChecks
2020/04/23 19:00:57: ERROR: null(0): EventId=1 Priority=ERROR Job 357D35AD-647C-46A8-8B25-00513EF44CE9 : 
DSC Engine Error : 
	 **Error Message Pull server with url: 2c1a3a3a-89eb-4ca8-9df3-4ae4f02394b1.agentsvc.azure-automation.net responded with error code: 404 for module 'nxOMSAutomationWorker' version '1.6.9.2'.** 
	Error Code : 1 
2020/04/23 19:00:57: ERROR: null(0): EventId=1 Priority=ERROR Job 357D35AD-647C-46A8-8B25-00513EF44CE9 : 
This event indicates that failure happens when LCM is trying to get the configuration from pull server using download manager null. ErrorId is 1. **ErrorDetail is Pull server with url: 2c1a3a3a-89eb-4ca8-9df3-4ae4f02394b1.agentsvc.azure-automation.net responded with error code: 404 for module 'nxOMSAutomationWorker' version '1.6.9.2'.**

.....


any idea ?

**Comment by pentiumoverdrive** [comment]
Same here...

**Comment by pentiumoverdrive** [comment]
After a day it started working again:

VERBOSE from InstallModule.py: Extracting module zip file from /tmp/filenVt9M6/nxOMSAutomationWorker_1.6.9.2.zip to /opt/microsoft/omsconfig/modules

update_mgmt_health_check.py now says:

Passed: Hybrid worker package is present
Passed: Hybrid worker is running

**Comment by larry-b-it** [comment]
Hi,
the same, it has been starting to work since to day. I think MS fixed something on their side because I had the issue since the whole last week

**Comment by tudorsibiu90** [comment]
in my case, it was the Python version. i had python2 and 3, but the MS scripts wanted python, so if you do a which python and it finds nothing, it will install most stuff but not the modules folder. Don't even ask how long it took me to figure this one out.

**Comment by OursonBleu** [comment]
For anyone else who had a similar issue like me.

1. Make sure that the VM is attached to workgroup/automation account.
2. Make sure that the Automation Account --> Update Management is enabled. 
3. Package should automatically be downloaded on the VM and installed. If it doesn't install automatically, try a reboot and if it doesn't work, you can manually do it.

**Comment by hestolz** [comment]
Thank you for your submission. As [previously announced](https://azure.microsoft.com/en-us/updates/were-retiring-the-log-analytics-agent-in-azure-monitor-on-31-august-2024/), the Log Analytics agent has been **deprecatated** and has no support as of **August 31, 2024.** If you use the Log Analytics agent to ingest data to Azure Monitor, [migrate now to the new Azure Monitor agent](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-migration). As part of repo archival, open issues and pull requests will be closed.
