### ISSUE TITLE
Firewall issues

### ISSUE THREAD

**Issue by sjohner** [Microsoft/OMS-Agent-for-Linux#9]
I am experiencing issues with OMS agent and firewall enabled on my Ubuntu 15.10 box. Can you elaborate on which ports have to be accessible by OMS agent to work properly. Currently getting the following messages with firewall enabled:

systemd[1]: Stopping Operations Management Suite agent...
systemd[1]: omsagent.service: Main process exited, code=killed, status=9/KILL
systemd[1]: Stopped Operations Management Suite agent.
systemd[1]: omsagent.service: Unit entered failed state.
systemd[1]: omsagent.service: Failed with result 'signal'.

**Comment by aspradhan** [comment]
Check out this article https://technet.microsoft.com/en-US/library/mt484101.aspx It lists all the required ports to be opened. I'll summarize here:

For the Microsoft Monitoring Agent to connect to and register with the OMS service, it must have access to the port number of your domains and the URLs. If you use a proxy server for communication between the agent and the OMS service, you’ll need to ensure that the appropriate resources are accessible. If you use a firewall to restrict access to the Internet, you need to configure your firewall to permit access to OMS. The following tables list the ports that OMS needs.




Agent Resource | Port
------------ | -------------
*.ods.opinsights.azure.com | Port 443 
*.oms.opinsights.azure.com | Port 443 
ods.systemcenteradvisor.com | Port 443 
*.blob.core.windows.net/ | Port 443

**Comment by jeffaco** [comment]
Thanks for your interest in the OMS Agent for Linux.

The messages you indicated are, unfortunately, normal behavior. Due to a technical problem with a plugin that we use, our service won't respond properly to signals. Thus, to shut down the service, we resort to doing a 'kill -9' on it. This results in the systemd messages that you saw above.

This does not reflect a failure of the agent; this is normal for any service that is killed via the 'kill -9' mechanism on a systemd system, even though systemd itself can trigger the signal if so configured.

We plan on changing this mechanism in a future release, which will eliminate these messages from systemd.

I'm going to close this issue since I believe I've answered your question. If you have further questions, please open a new issue or, if directly related, reopen this one.

**Comment by sjohner** [comment]
Thanks guys! In the meantime I figured that its probably not a firewall issue. Thanks for clarification on this!
