### ISSUE TITLE
No heartbeat data after successful onboarding, but syslog data OK - Physical Linux server, RHEL/CentOS 7.x 

### ISSUE THREAD

**Issue by gd-ksc** [microsoft/OMS-Agent-for-Linux#925]
Hello.  

In our environment, we have two physical Linux servers running either RHEL 7.x or CentOS 7.x, 

After successfully installing the Agent for Linux, via the wget command provided on Azure Portal, we do not see Heartbeat data in the Log Analytics workspace.

We are installing the following version via the Azure Portal:

>> omsagent-1.9.0-0.universal.x64.sh

The Agent installs OK, starts OK, and reports that it's onboarded:

>> ... Status: Onboarded(OMSAgent Running)

The workspace's omsagent.log shows Heartbeat succeeded messages every 60 seconds:

>>  ... [info]: Sending OMS Heartbeat succeeded at...

However, we never see Heartbeat data in the Log Analytics workspace.

Interestingly, syslog configuration works, and syslog data is current in Log Analytics.

This issue is not seen on Virtual Machines in the environment.

Any guidance would be appreciated.

Thanks.

**Comment by gd-ksc** [comment]
I've tracked this issue to a bad UUID in the following file:

> /etc/opt/microsoft/omsagent/<I>WS</I>/conf/omsadmin.conf

Example of bad UUID:

> UUID=37e9709c-f790-11e3-a948-6cae8b34bc70SerialNumber:-[UUID:61A44E990EE9523C8E0161D175FC0A75]-

During install, when the following script ran, two UUID lines were returned by dmidecode (e.g. blade and enclosure), so the two UUID lines were concatenated:

https://github.com/Microsoft/OMS-Agent-for-Linux/blob/57ad234810f50c9969851ddb28a9ea23e8fc0ce6/installer/scripts/omsadmin.sh#L543

To resolve locally, I manually corrected the UUID within the WS omsadmin.conf, then restarted the omsagent service.  After that, the computer showed connected in the Log Analytics workspace, and the Heartbeat data appeared in queries.

To fix the script, perhaps consider modifying the dmidecode command, so that it leverages the option to filter by keyword, system-uuid:

> UUID=\`dmidecode -s system-uuid\`

Thanks.

**Comment by hestolz** [comment]
Hi Garry, thanks for your feedback. The issue was on our radar and will be fixed in the upcoming release, ETA < 1 month.

**Comment by ramprasathrk** [comment]
Hello @hestolz,
I know this issue is  an old issue, but as mentioned by @k17034 the relevant fix is not made on the [omsadmin.sh](https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/omsadmin.sh#L560) yet.

Running `dmidecode | grep UUID` returns multiple UUIDs, for example: i received this:
```
UUID: 4c488a00-cc15-11eb-8000-3cedefb67e66
                Service UUID: c45cab2a-7de0-45f4-8b3b-726c3774b26b
```

and Garry received something similar: 

`UUID=37e9709c-f790-11e3-a948-6cae8b34bc70SerialNumber:-[UUID:61A44E990EE9523C8E0161D175FC0A75]-`

Due to [this regex validation](https://github.com/microsoft/OMS-Agent-for-Linux/pull/913/commits), i don't get the proper VMUUID in hearbeat data in Log Analytics Workspace. It's always "00000000-0000-0000-0000-000000000000".

So i believe dmidecode command should be modified to get exact system UUID, may be like @k17034 's suggestion: `UUID=`dmidecode -s system-uuid``
